### ISSUE TITLE
Issue during install

### ISSUE THREAD

**Issue by snaptom** [99designs/ecs-cli#13]
Hey folks,

I was wondering if you might be able to give me a couple of pointers - I have been trying to install and run the CLI but I hit the below message while running

```
go get github.com/99designs/ecs-cli
```

```
# github.com/99designs/ecs-cli/compose
src/github.com/99designs/ecs-cli/compose/transform.go:26: not enough arguments in call to docker.NewProject
src/github.com/99designs/ecs-cli/compose/transform.go:32: project.Configs undefined (type project.APIProject has no field or method Configs)
src/github.com/99designs/ecs-cli/compose/transform.go:33: project.Configs undefined (type project.APIProject has no field or method Configs)
```
All the best and thanks,
Tom.

**Comment by lox** [comment]
Sounds like you don't have the right version of docker's libcompose. There is now a glide lockfile for this project, I'd suggest installing glide and running `glide install` in the project directory.

**Comment by snaptom** [comment]
Thanks, appreciate your reply. I have tried this now too - I don't suppose you have seen a situation where glide just hangs on a particular package? I can't get it past kingpin.v2. unfortunately.

```
[INFO] Fetching updates for golang.org/x/net.
[INFO] Fetching updates for golang.org/x/sys.
[INFO] Fetching updates for gopkg.in/alecthomas/kingpin.v2.
```

Cheers.

**Comment by lox** [comment]
Nope, sorry haven't encountered that one. Do you have the latest glide installed? Might be worth enabling a verbose mode if there is one.

**Comment by snaptom** [comment]
Thanks! Turns out I was just being impatient - the glide install just took ages for some reason!
